# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright (c) 2025 Sylvex. All rights reserved.
#
# TRAP Configuration Example
# ==========================
#
# This file demonstrates the complete configuration schema for TRAP
# (Transparent Rust Adapter for industrial Protocols).
#
# Copy this file to trap.yaml and modify as needed.

# =============================================================================
# Gateway Configuration
# =============================================================================
gateway:
  # Unique gateway identifier (required)
  id: "trap-gateway-01"

  # Human-readable name
  name: "TRAP Gateway - Building A"

  # Description
  description: "Main data collection gateway for Building A"

  # Physical location
  location: "Server Room, Floor 1"

  # Custom metadata (optional)
  metadata:
    site: "headquarters"
    zone: "production"
    maintainer: "ops-team@example.com"

# =============================================================================
# Device Configurations
# =============================================================================
devices:
  # -------------------------
  # Modbus TCP Example
  # -------------------------
  - id: "plc-001"
    name: "Main PLC"
    description: "Siemens S7-1200 PLC"
    enabled: true

    # Protocol configuration
    protocol:
      type: modbus_tcp
      host: "192.168.1.100"
      port: 502
      unit_id: 1

    # Polling settings
    poll_interval_ms: 1000
    timeout_ms: 5000
    retry_count: 3

    # Tag definitions
    tags:
      - id: "temperature"
        name: "Room Temperature"
        address: "HR:100"          # Holding Register 100
        data_type: float32
        unit: "°C"
        writable: false
        min_value: -40.0
        max_value: 85.0
        scale: 0.1                 # Raw value * 0.1 = actual value

      - id: "humidity"
        name: "Room Humidity"
        address: "HR:102"          # Holding Register 102
        data_type: uint16
        unit: "%"
        writable: false

      - id: "power_consumption"
        name: "Power Consumption"
        address: "HR:200:2"        # Holding Register 200, count 2 (32-bit)
        data_type: float32
        unit: "kW"
        writable: false

      - id: "setpoint"
        name: "Temperature Setpoint"
        address: "HR:300"
        data_type: float32
        unit: "°C"
        writable: true             # Allows write operations
        min_value: 18.0
        max_value: 28.0

      - id: "pump_status"
        name: "Pump Running Status"
        address: "C:0"             # Coil 0
        data_type: bool
        writable: true

      - id: "alarm_active"
        name: "Alarm Active"
        address: "DI:10"           # Discrete Input 10
        data_type: bool
        writable: false

  # -------------------------
  # Modbus RTU Example
  # -------------------------
  - id: "meter-001"
    name: "Energy Meter"
    description: "Schneider PM5000 Power Meter"
    enabled: true

    protocol:
      type: modbus_rtu
      port: "/dev/ttyUSB0"         # Serial port
      baud_rate: 9600
      data_bits: 8
      stop_bits: 1
      parity: none                 # none, odd, even
      unit_id: 1

    poll_interval_ms: 5000
    timeout_ms: 3000
    retry_count: 2

    tags:
      - id: "voltage_l1"
        name: "Voltage L1-N"
        address: "IR:0"            # Input Register 0
        data_type: float32
        unit: "V"

      - id: "current_l1"
        name: "Current L1"
        address: "IR:2"
        data_type: float32
        unit: "A"

      - id: "active_power"
        name: "Active Power"
        address: "IR:10"
        data_type: float32
        unit: "kW"

      - id: "energy_total"
        name: "Total Energy"
        address: "IR:100:2"
        data_type: float64
        unit: "kWh"

  # -------------------------
  # OPC UA Example
  # -------------------------
  - id: "scada-001"
    name: "SCADA Server"
    description: "Ignition SCADA OPC UA Server"
    enabled: true

    protocol:
      type: opc_ua
      endpoint_url: "opc.tcp://192.168.1.50:4840"
      security_policy: Basic256Sha256
      security_mode: SignAndEncrypt
      username: "${OPCUA_USERNAME:admin}"           # Environment variable with default
      password: "ENC:abc123..."                      # Encrypted password
      # certificate_path: "./certs/client.pem"       # Optional client certificate
      # private_key_path: "./certs/client.key"

    poll_interval_ms: 500
    timeout_ms: 10000
    retry_count: 3

    tags:
      - id: "tank_level"
        name: "Tank Level"
        address: "ns=2;s=Tanks.Tank1.Level"
        data_type: float64
        unit: "m"

      - id: "valve_position"
        name: "Valve Position"
        address: "ns=2;i=1001"                     # Numeric node ID
        data_type: float32
        unit: "%"
        writable: true

      - id: "system_status"
        name: "System Status"
        address: "ns=2;s=System.Status"
        data_type: int32

  # -------------------------
  # BACnet IP Example
  # -------------------------
  - id: "hvac-001"
    name: "HVAC Controller"
    description: "Tridium Niagara JACE"
    enabled: true

    protocol:
      type: bac_net_ip
      host: "192.168.1.200"
      port: 47808
      device_instance: 12345

    poll_interval_ms: 2000
    timeout_ms: 5000
    retry_count: 2

    tags:
      - id: "zone_temp"
        name: "Zone Temperature"
        address: "AI:0"                            # Analog Input, instance 0
        data_type: float32
        unit: "°C"

      - id: "supply_temp"
        name: "Supply Air Temperature"
        address: "AI:1"
        data_type: float32
        unit: "°C"

      - id: "damper_position"
        name: "Damper Position"
        address: "AO:0"                            # Analog Output
        data_type: float32
        unit: "%"
        writable: true

      - id: "fan_status"
        name: "Fan Status"
        address: "BI:0"                            # Binary Input
        data_type: bool

      - id: "fan_command"
        name: "Fan Command"
        address: "BO:0"                            # Binary Output
        data_type: bool
        writable: true

      - id: "zone_temp_setpoint"
        name: "Zone Setpoint"
        address: "AV:0"                            # Analog Value
        data_type: float32
        unit: "°C"
        writable: true
        min_value: 18.0
        max_value: 28.0

  # -------------------------
  # KNX IP Example
  # -------------------------
  - id: "lighting-001"
    name: "Lighting Controller"
    description: "KNX IP Router"
    enabled: false                                  # Disabled by default

    protocol:
      type: knx
      host: "192.168.1.250"
      port: 3671
      connection_type: tunneling                   # tunneling or routing

    poll_interval_ms: 1000
    timeout_ms: 3000
    retry_count: 2

    tags:
      - id: "light_level"
        name: "Light Level Zone A"
        address: "1/2/3"                           # 3-level group address
        data_type: uint8
        unit: "%"
        writable: true

      - id: "light_status"
        name: "Light Status"
        address: "1/2/4"
        data_type: bool
        writable: true

# =============================================================================
# Buffer Configuration
# =============================================================================
buffer:
  # Storage directory (relative to config file)
  path: "./data/buffer"

  # Maximum buffer size (1GB)
  max_size_bytes: 1073741824

  # Maximum number of items
  max_items: 10000000

  # Enable LZ4 compression
  compression: true

  # Data retention in days
  ttl_days: 7

  # Flush configuration
  flush:
    interval_secs: 60                              # Flush every 60 seconds
    batch_size: 1000                               # Items per batch
    retries: 3                                     # Retry attempts
    retry_delay_ms: 1000                           # Initial retry delay
    max_retry_delay_secs: 60                       # Maximum retry delay
    endpoint: "${UPSTREAM_ENDPOINT:http://localhost:8081/api/v1/data}"

  # Circuit breaker for upstream connection
  circuit_breaker:
    failure_threshold: 5                           # Open after 5 failures
    reset_timeout_secs: 30                         # Try again after 30 seconds
    half_open_max_calls: 3                         # Test requests in half-open
    success_rate_threshold: 0.5                    # 50% success rate to close

# =============================================================================
# API Configuration
# =============================================================================
api:
  enabled: true
  bind_address: "0.0.0.0"
  port: 8080
  base_path: "/api/v1"

  # Request settings
  request_timeout_secs: 30
  max_body_size: 10485760                          # 10MB

  # CORS configuration
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "https://dashboard.example.com"
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed_headers:
      - Content-Type
      - Authorization
    allow_credentials: true
    max_age_secs: 3600

# =============================================================================
# Security Configuration
# =============================================================================
security:
  # JWT Authentication
  jwt:
    enabled: true
    # Secret key (should be encrypted in production)
    # Generate with: openssl rand -base64 32
    secret: "ENC:encrypted-jwt-secret-here"        # Use encryption
    expiration_secs: 3600                          # 1 hour
    issuer: "trap"
    algorithm: HS256                               # HS256, HS384, HS512, RS256, etc.
    public_paths:
      - "/health"
      - "/ready"
      - "/metrics"
      - "/api/v1/auth/login"

  # TLS Configuration (optional)
  # Uncomment to enable HTTPS
  # tls:
  #   cert_path: "./certs/server.crt"
  #   key_path: "./certs/server.key"
  #   ca_cert_path: "./certs/ca.crt"              # For client cert verification
  #   require_client_cert: false
  #   min_version: "1.2"                          # 1.2 or 1.3

  # Rate Limiting
  rate_limit:
    enabled: true
    requests_per_second: 100
    burst_size: 50
    per_ip: true
    per_user: false

  # Audit Logging
  audit:
    enabled: true
    path: "./logs/audit.log"
    retention_days: 30
    rotation: daily                                # daily, size, never
    events:
      - login
      - logout
      - write
      - config_change

# =============================================================================
# Logging Configuration
# =============================================================================
logging:
  level: info                                      # trace, debug, info, warn, error
  format: pretty                                   # pretty, compact, full, json
  stdout: true
  file: "./logs/trap.log"
  json: false                                      # Structured JSON logging
  with_target: true                                # Include module path
  with_file: false                                 # Include file:line
  with_thread_ids: false                           # Include thread IDs
